"""add ocr status columns

Revision ID: 272509356546
Revises: b65e363410b7
Create Date: 2026-10-04 02:59:28.830327
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '272509356546'
down_revision: Union[str, None] = 'b65e363410b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ocr_edited', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_column('ocr_edited')
        batch_op.drop_column('ocr_error')

    # ### end Alembic commands ###
